config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="main"),
    path("generic/", TemplateView.as_view(template_name="generic.html"), name="generic"),
    path("elements/", TemplateView.as_view(template_name="elements.html"),
         name="elements"),
    path("todo_list/", include('todo_list.urls')),
    path("board/", include('board.urls')),
    path("find/", include('find.urls')),
    # path("chat/", include('chat.urls') ),
    path("community/", include('community.urls')),
    path("maps/", include('map.urls')),
    # path("ranking/", include('ranking.urls') ),
    path("todo_list/", include('todo_list.urls')),
    path("users/", include('user.urls')),
    path("volunteer/", include('volunteer.urls')),

    # google login
    path("accounts/", include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

map/urls.py
from django.urls import path
from .import views
# from board.views import list


urlpatterns = [
    path("", views.maps, name="maps"),
]

volunteer/urls.py
from django.urls import path
from . import views
# from board.views import list


urlpatterns = [
    path("", views.vol_index, name="vol_index"),
    path("<int:pk>", views.vol_detail, name="vol_detail"),
    path("<int:pk>/sign", views.sign_vol, name="sign_vol"),
    path("<int:pk>/add_cal", views.add_cal, name="add_cal"),
    path("create_vol", views.create_vol, name="create_vol"),
    path("create_org", views.create_org, name="create_org"),
]

volunteer/models.py
import datetime
from django.utils import timezone

from django.db import models
from user.models import User

# Create your models here.


class Organization(models.Model):
    org_name = models.CharField(max_length=15, verbose_name="단체 및 시설 이름")
    addr = models.CharField(max_length=100, verbose_name="주소")
    director = models.CharField(max_length=15, verbose_name="담당자")
    phone_num = models.CharField(max_length=15, verbose_name="담당자 연락처")

    def __str__(self) -> str:
        return "%s" % (self.org_name)


class Volunteer(models.Model):
    title = models.CharField(max_length=30, verbose_name="제목")
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, verbose_name="봉사단체")
    content = models.TextField(null=True, default="")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="등록일")
    image = models.ImageField(blank=True, null=True, verbose_name="이미지")
    updated_at = models.DateTimeField(auto_now=True)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    sign_vol = models.ManyToManyField(User, related_name='sign_up', verbose_name='신청')

volunteer/forms.py
from django import forms
from .models import Volunteer,Organization


class VolunteerForm(forms.ModelForm):
    class Meta:
        model = Volunteer
        fields = ["title", "organization", "content", "image","start_date","end_date"]

class OrganizationForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = "__all__"

volunteer/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Volunteer
from .forms import VolunteerForm ,OrganizationForm
from todo_list.forms import TodoForm
from todo_list.models import Todo
from datetime import datetime
from django.utils.dateformat import DateFormat
from django.db.models import Q

# Create your views here.

@login_required(login_url="login")
def vol_index(request):
    vol_list = Volunteer.objects.all()
    today = DateFormat(datetime.now()).format('Y-m-d H:i')
    todo = Todo.objects.filter(user_id = request.user.id).filter(~Q(vol_id=0)).filter(complete=1)
    vol_id = todo.values("vol_id")
    print(vol_id)
    
    return render(request, "volunteer/index.html", {"vol_list": vol_list,"today":today,"vol_id":vol_id})


@login_required(login_url="login")
def vol_detail(request,pk):
    detail = get_object_or_404(Volunteer,pk=pk)
    return render(request, 'volunteer/vol_detail.html', {'detail':detail})

@login_required(login_url="login")
def sign_vol(request, pk):
    sign_vol = get_object_or_404(Volunteer, pk=pk)
    sign_vol.sign_vol.add(request.user)

    return redirect("vol_detail", pk=pk)

@login_required(login_url="login")
def add_cal(request,pk):
    vol_detail = get_object_or_404(Volunteer,pk=pk)
    Todo.objects.create(
    title= vol_detail.organization.org_name,
    start_date= vol_detail.start_date,
    end_date =  vol_detail.end_date,
    description =  vol_detail.organization.addr,
    user = request.user,
    vol_id = vol_detail.id
    )
    
    return redirect("todo_list")

@login_required(login_url="login")
def create_vol(request):
    if request.method == "POST":
        form = VolunteerForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            
            return redirect("vol_index")
    else:
        form = VolunteerForm()

    return render(request, "volunteer/create_vol.html", {"form": form})

@login_required(login_url="login")
def create_org(request):
    if request.method == "POST":
        form = OrganizationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("vol_index")
    else:
        form = OrganizationForm()

    return render(request, "volunteer/create_org.html", {"form": form})

templates/volunteer/create_org.html
{% extends 'base.html' %}
{% block contents %}
  <div class="container" style="margin-top:5rem">
    {% include "form_errors.html" %}
    <!-- 폼 요소에 type='file' 포함이 되어 있다면 form enctype(인코딩타입) 속성 필요함 text 형태의 데이터 전송 시 enctype 타입은 application/x-www-form-urlencode(기본) 설정되어있음 -->

    <form method="POST" class="col-lg-8 col-md-10 mx-auto" enctype="multipart/form-data">
      {% csrf_token %}
      <h3 class="pb-2 mt-5">
        <strong>봉사활동 추가</strong>
      </h3>
      <hr/>
      <div class="form-group my-2 col">
        <label for="org_name" class="form-label">단체 및 시설 이름</label>
        <input type="text" name="org_name" id="org_name" class="form-control" value=""/>
      </div>
      <div class="form-group my-2 col">
        <label for="addr" class="form-label">주소</label>
        <input type="text" name="addr" id="addr" class="form-control" value=""/>
      </div>
      <div class="form-group my-2 col">
        <label for="director" class="form-label">담당자</label>
        <input type="text" name="director" id="director" class="form-control" value=""/>
      </div>
      <div class="form-group my-2 col">
        <label for="phone_num" class="form-label">담당자 연락처</label>
        <input type="text" name="phone_num" id="phone_num" class="form-control" value=""/>
      </div>
      <div class="form-group my-3">
        <button class="btn text-white" style="background-color:#675444; color:#fff" type="submit">
          생성하기
        </button>
      </div>
    </div>
  </form>
</div>
{% endblock contents %}

templates/volunteer/create_vol.html
{% extends 'base.html' %}
{% block contents %}
  <div class="container">
    {% include "form_errors.html" %}
    <!-- 폼 요소에 type='file' 포함이 되어 있다면 form enctype(인코딩타입) 속성 필요함 text 형태의 데이터 전송 시 enctype 타입은 application/x-www-form-urlencode(기본) 설정되어있음 -->

    <form method="POST" class="col-lg-8 col-md-10 mx-auto" enctype="multipart/form-data">
      {% csrf_token %}
      <h3 class="pb-2 mt-5">
        <strong>봉사활동 추가</strong>
      </h3>
      <hr/>
      <div class="form-group my-2 col">
        <label for="title" class="form-label">제목</label>
        <input type="text" name="title" id="title" class="form-control" value=""/>
        <div class="form-group my-2">
          <label for="content" class="form-label">내용</label>
          <textarea name="content" id="content" rows="7" class="form-control"></textarea>
          <div class="form-group my-2">
            <label for="content" class="form-label">업체</label>
            {{form.organization}}
          </div>
        </div>
        <div class="form-group my-2">
          <label for="image" class="form-label">사진첨부</label>
          <input type="file" name="image" id="image" class="form-control" value=""/>
        </div>
        <div class="form-group my-2">
          <label for="start_date" class="form-label">시작일시</label>
          <input type="datetime-local" id="start_date" class="form-control" name="start_date"/>
        </div>
        <div class="form-group my-2">
          <label for="end_date" class="form-label">종료일시</label>
          <input type="datetime-local" id="end_date" class="form-control" name="end_date"/>
        </div>
        <div class="form-group my-3">
          <button class="btn text-white" style="background-color:#675444; color:#fff" type="submit">
            생성하기
          </button>
        </div>
      </div>
    </form>
  </div>
{% endblock contents %}
{% block script %}
  <script>
    document
      .querySelector("#id_organization")
      .classList
      .add("form-control")
  </script>
{% endblock script %}

templates/volunteer/index.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
  <style>
    .completed {
      width: 16rem;
      object-fit: cover;
      position: absolute;
      top: -1rem;
      left: 3rem;
    }

    .theend {
      width: 15rem;
      object-fit: cover;
      position: absolute;
      top: 0;
      left: 4rem;
    }

    .fa-solid {
      color: #675444;
    }
  </style>
  <script src="https://kit.fontawesome.com/482f2e22f6.js" crossorigin="anonymous"></script>
{% endblock style %}

{% block contents %}
  <div class="container my-3 mb-5">
    <div class='pt-5'>
      <div class="d-flex justify-content-center mt-3 mb-5">
        <a href="{% url 'vol_index' %}" class='list' style="text-decoration:none; color:black">
          <h1>
            <i class="fa-solid fa-paw"></i>
            <strong>Volunteer</strong>
            <i class="fa-solid fa-paw"></i>
          </h1>
        </a>
      </div>
      <hr style="width:40rem; margin: 0 auto;"/>
    </div>
    <div class="row  justify-content-center">
      <div class="col-10">
        {% if user.is_authenticated and user.is_superuser %}
          <div class="row justify-content-end">
            <div class="col-md-2 my-5">
              <a href="{% url 'create_vol' %}" class="btn mx-auto d-block " style="background-color:#675444; color:#fff">일정 생성</a>
            </div>
            <div class="col-md-2 my-5">
              <a href="{% url 'create_org' %}" class="btn mx-auto d-block" style="background-color:#675444; color:#fff">업체 등록</a>
            </div>
          {% endif %}
          {% for list in vol_list %}
            <div class="card mb-3 p-0">
              <div class="row g-0">
                <div class="col-md-4">
                  <a href="{% url 'vol_detail' list.id %}" class="detail_url">
                    <img src="{{list.image.url }}" class="img-fluid rounded-start" alt="..." style="height: 242px;">
                  </a>
                  {%if list.end_date|date:'Y-m-d H:i' < today %}
                    <img src="{% static 'img/The_end.png' %}" alt="" class="theend">
                  {%endif%}
                  {%for i in vol_id%}
                    {%if i.vol_id == list.id %}
                      <img src="{% static 'img/comp.png' %}" alt="" class="completed">
                    {%endif%}
                  {% endfor %}

                    </div>
                    <div class="col-md-8">
                      <div class="card-body">
                          <h2 class="card-title" style="text-decoration:none; color:#000">
                            <strong>{{list.title}}</strong>
                          </h2>
                        </a>
                        <div class="card-text">
                          <p>
                            단체 및 시설 이름 :
                            {{list.organization}}</br>
                          주소 :
                          {{list.organization.addr}}</br>
                        <p class="date">신청 기간 :
                          {{list.start_date|date:'Y-m-d H:i'}}
                          ~
                          {{list.end_date|date:'Y-m-d H:i'}}
                        </p>
                        <small class="text-muted">
                          등록일 :
                          {{list.created_at}}</small>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  {% endblock contents %}
  {% block script %}
    <script>
      let deadline = document.querySelectorAll(".date")
      deadline.forEach((date, idx) => {
        end_date = date
          .innerText
          .split("~")[1];
        let end = new Date(end_date)
        let today = new Date("{{today}}")
        if (end < today) {
          let link = document.querySelectorAll(".detail_url")
          link[idx].addEventListener("click", (e) => {
            e.preventDefault();
            alert("이미종료된 활동 입니다.")
          })
        }
      })
    </script>
  {% endblock script %}

templates/volunteer/vol_detail.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  <style>
    .order {
      text-decoration: none;
      color: inherit;
    }
  </style>
{% endblock style %}
{% block contents %}
  {% include "form_errors.html" %}
  <div class="container" style="width:65%">

    <div class="pt-3">
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <p class="card-text"></p>
      </div>
      <div class="row mt-5 pt-3">
        <div class='row mt-3 mb-1'>
          <div class="col-4">
            <h3 class="pb-2">
              <b>제목 :
                {{detail.title}}</b>
            </h3>
          </div>
        </div>
        <hr class='one mb-1'>
        <div class="d-flex flex-row justify-content-between mb-5">
          <div class="py-2 text-muted">
            <span>({{detail.created_at|date:'Y-m-d H:i'}})</span>
          </div>
          {% if detail.updated_at %}
            <div class="pt-1">
              <div class="py-2 text-muted">
                <!-- 수정날짜 -->
                <div class="text-start">(수정 :
                  {{detail.updated_at|date:'Y-m-d H:i'}})</div>
              </div>
            </div>
          {% endif %}
        </div>
        <div class="col-12 mt-2 mb-5">
          {% if detail.image %}
            <img class='mx-auto d-block detail_img' src="{{detail.image.url}}" alt="">
          {% endif %}
        </div>
        <div class="col-12">
          <!--본문-->
          <p>
            단체 및 시설 이름 :
            {{detail.organization}}</br>
          주소 :
          {{detail.organization.addr}}</br>
        <p class="date">신청 기간 :
          {{detail.start_date|date:'Y-m-d H:i'}}
          ~
          {{detail.end_date|date:'Y-m-d H:i'}}
        </p>
      </p>
      <div class="row justify-content-end">
        <div class="col-2 mt-4">
          <a href="#" data-uri="{% url 'sign_vol' detail.id %}" class="sign_vol btn mx-auto d-block col" style="background-color:#675444;color:#fff">신청하기</a>
        </div>
        <div class="col-2 mt-4">
          <a href="{% url 'vol_index' %}" class="sign_vol btn mx-auto d-block col" style="background-color:#675444;color:#fff">목록으로</a>
        </div>
        <hr class='one mt-4 mb-5'>
      </div>
    </div>
  </div>
{% endblock contents %}
{% block script %}
  <script>
    document
      .querySelector(".sign_vol")
      .addEventListener('click', (e) => {
        if (confirm('잠여하시겠습니까?')) {
          e.preventDefault();
          location.href = e.target.dataset.uri
          if (confirm("캘린더에 일정을 추가하시겠습니까?")) {
            location.href = "{% url 'add_cal' detail.id %}"
          }
        }
      })
  </script>
{% endblock script %}