community/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.post_list, name="post_list"),
    ### post
    path("post/write/", views.post_write, name="post_write"),
    path("<int:post_id>/", views.post_detail, name="post_detail"),
    path("post/edit/<int:post_id>/", views.post_edit, name="post_edit"),
    path("post/delete/<int:post_id>/", views.post_delete, name="post_delete"),
    # path("post/like/", views.post_like, name='post_like'),
    ### answer
    path("answer/write/<int:post_id>/", views.answer_write, name="answer_write"),
    path("answer/edit/<int:answer_id>/", views.answer_edit, name="answer_edit"),
    path("answer/delete/<int:answer_id>/", views.answer_delete, name="answer_delete"),
    ### comment
    path(
        "comment/write/answer/<int:answer_id>/",
        views.comment_write,
        name="comment_write",
    ),
    path(
        "comment/edit/answer/<int:comment_id>/", views.comment_edit, name="comment_edit"
    ),
    path(
        "comment/delete/answer/<int:comment_id>/",
        views.comment_delete,
        name="comment_delete",
    ),
    ### vote
    # http://127.0.0.1:8000/board/question/vote/1/
    path("question/vote/<int:post_id>/", views.vote_post, name="vote_post"),
    path("answer/vote/<int:answer_id>/", views.vote_answer, name="vote_answer"),
    path("comment/vote/<int:comment_id>/", views.vote_comment, name="vote_comment"),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="main"),
    path("generic/", TemplateView.as_view(template_name="generic.html"), name="generic"),
    path("elements/", TemplateView.as_view(template_name="elements.html"),
         name="elements"),
    path("todo_list/", include('todo_list.urls')),
    path("board/", include('board.urls')),
    path("find/", include('find.urls')),
    # path("chat/", include('chat.urls') ),
    path("community/", include('community.urls')),
    path("maps/", include('map.urls')),
    # path("ranking/", include('ranking.urls') ),
    path("todo_list/", include('todo_list.urls')),
    path("users/", include('user.urls')),
    path("volunteer/", include('volunteer.urls')),

    # google login
    path("accounts/", include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

map/urls.py
from django.urls import path
from .import views
# from board.views import list


urlpatterns = [
    path("", views.maps, name="maps"),
]

community/models.py
from django.db import models
from user.models import User
from django.db.models import UniqueConstraint
from django.template.defaultfilters import slugify
from django.urls import reverse

class BaseModel(models.Model):
    created_at = models.DateTimeField(verbose_name='작성날짜', auto_now_add=True)
    modified_at = models.DateTimeField(verbose_name='수정날짜', auto_now=True)
    
    class Meta:
        abstract = True
    
    
class Post(BaseModel):
    title = models.CharField(max_length=200, verbose_name='제목')
    writer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='작성자', related_name='writer_post')
    content = models.TextField(verbose_name='내용')
    view_cnt = models.BigIntegerField(default=0)
    vote = models.ManyToManyField(User, related_name='vote_post', verbose_name='추천수')
    
    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse("post_detail", args=[self.pk])
    
    def get_previous(self):
        return self.get_previous_by_created_at()
    
    def get_next(self):
        return self.get_next_by_created_at()
    
    
# image file naming
# instance => 현재 정의된 모델의 인스턴스 
# filename => 파일에 원래 제공된 파일 이름. 이것은 최종 목적지 경로를 결정할 때 고려되거나 고려되지 않을 수 있음
def image_upload_to(instance, filename):
    # 해당 Post 모델의 title 을 가져옴
    title = instance.post.title
    # slug - 의미있는 url 사용을 위한 필드.
    # slugfy 를 사용해서 title을 slug 시켜줌.
    slug = slugify(title)
    # 제목 - 슬러그된 파일이름 형태
    return "post_images/%s-%s" % (slug, filename)


class Image(BaseModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="작성글", related_name="image")
    image = models.ImageField(upload_to=image_upload_to)

    class Meta:
        # 단수
        verbose_name = 'Image'
        # 복수
        verbose_name_plural = 'Images'

    # 이것도 역시 post title 로 반환
    def __str__(self):
       return str(self.post)


class PostCount(models.Model):
    ip = models.CharField(max_length=30)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    
    def __unicode__(self):
        return self.ip
    
    
class Answer(BaseModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(verbose_name='댓글')
    writer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='작성자', related_name='writer_answer')
    vote = models.ManyToManyField(User, related_name='vote_answer', verbose_name='추천수')
    
    
class Comment(BaseModel):
    writer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='작성자',related_name='writer_comment')
    content = models.TextField(verbose_name='대댓글')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True, blank=True)
    vote = models.ManyToManyField(User, related_name='vote_comment', verbose_name='추천수')

community/forms.py
from django import forms
from .models import Post, Answer, Comment, Image
from django.utils.translation import gettext_lazy as _

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content"]


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ["content"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('image', )
        labels = {
            'image': _('Image'),
            
        }

community/views.py
from django.shortcuts import render, redirect, get_object_or_404, resolve_url

from .models import Post, PostCount, Answer, Comment, Image
from .forms import PostForm, AnswerForm, CommentForm, ImageForm

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from django.db.models import Q, Count
from tools.utils import get_client_ip

from django.contrib import messages

from django.forms import modelformset_factory


##### post #####

# 리스트
def post_list(request):

    post_list = Post.objects.order_by("-created_at")

    # 검색조건,검색어 받기
    search_kind = request.GET.get("search_kind", "")
    keyword = request.GET.get("keyword", "")

    # 정렬기준 받기
    so = request.GET.get("so", "recent")

    # 정렬
    if so == "recommend":
        # 추천 많은 순서
        post_list = Post.objects.annotate(num_vote=Count("vote")).order_by(
            "-num_vote", "-created_at"
        )
    elif so == "popular":
        # 답변 많은 순서
        post_list = Post.objects.annotate(num_answer=Count("answer")).order_by(
            "-num_answer", "-created_at"
        )
    else:
        # 최신글부터
        post_list = Post.objects.order_by("-created_at")

    if keyword:
        if len(keyword) > 1:
            if search_kind == 'all':
                post_list = post_list.filter(
                    Q(title__icontains=keyword) | 
                    Q(content__icontains=keyword) | 
                    Q(writer__email__icontains=keyword)).distinct()
            elif search_kind == "title":
                post_list = post_list.filter(
                    title__icontains=keyword).distinct()
            elif search_kind == "writer":
                post_list = post_list.filter(
                    writer__email__icontains=keyword).distinct()
            elif search_kind == "content":
                post_list = post_list.filter(
                    content__icontains=keyword).distinct()
        else:
            messages.error(request, "검색어는 2글자 이상 입력해주세요.")

    # 페이지
    page = request.GET.get("page", 1)

    paginator = Paginator(post_list, 10)
    page_obj = paginator.get_page(page)

    return render(
        request,
        "community/post_list.html",
        {
            "post_list": page_obj,
            "page": page,
            "so": so,
            "keyword": keyword,
            "search_kind": search_kind,
        },
    )


# 글작성
@login_required(login_url="login")
def post_write(request):

    # 하나의 modelform 을 여러번 쓸 수 있음. 모델, 모델폼, 몇 개의 폼을 띄울건지 갯수
    ImageFormSet = modelformset_factory(Image, form=ImageForm, extra=5)

    if request.method == 'POST':

        postForm = PostForm(request.POST)
        # queryset 을 none 으로 정의해서 이미지가 없어도 되도록 설정. none 은 빈 쿼리셋 리턴
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=Image.objects.none())

        # 두 모델폼의 유효성 검사를 해주고
        if postForm.is_valid() and formset.is_valid():
            post_form = postForm.save(commit=False)
            post_form.writer = request.user
            post_form.save()

            # 유효성 검사가 왼료된 formset 정리된 데이터 모음
            for form in formset.cleaned_data:
                if form:
                    # image file
                    image = form['image']
                    print(form)
                    print(form['image'])
                    # post, image file save
                    photo = Image(post=post_form, image=image)
                    photo.save()
            return redirect('post_list')
        # 유효성 검사 실패시 터미널상에 에러메시지 print
        else:
            print(postForm.errors, formset.errors)
    else:
        # POST 요청이 아닌 경우
        postForm = PostForm()
        formset = ImageFormSet(queryset=Image.objects.none())

    return render(request, 'community/post_write.html',
                  {'postForm': postForm, 'formset': formset})


# 상세내용
def post_detail(request, post_id):

    page = request.GET.get("page", 1)
    keyword = request.GET.get("keyword", "")
    so = request.GET.get("so", "recent")

    post = get_object_or_404(Post, id=post_id)

    # 조회수
    ip = get_client_ip(request)
    cnt = PostCount.objects.filter(ip=ip, post=post).count()

    if cnt == 0:
        post_cnt = PostCount(ip=ip, post=post)
        post_cnt.save()

        if post.view_cnt:
            post.view_cnt += 1
        else:
            post.view_cnt = 1
        post.save()

    return render(
        request,
        "community/post_detail.html",
        {"post": post, "page": page, "keyword": keyword, "so": so},
    )
    


# 수정
@login_required(login_url="login")
def post_edit(request, post_id):
    """
    이미 이미지가 있는 경우
    1. 이미지가 새롭게 들어오는 경우 - 기존 이미지 제거 후 새로운 이미지 삽입
    2. 이미지가 안들어오는 경우 - 기존 이미지 유지


    기존 내용에 이미지가 없는 경우
    1. 이미지가 새롭게 들어오는 경우 - (기존 이미지 제거 후) 새로운 이미지 삽입
    """

    post = get_object_or_404(Post, id=post_id)
    ImageFormSet = modelformset_factory(Image, form=ImageForm, extra=5)

    if request.method == 'POST':

        postForm = PostForm(request.POST, instance=post)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=Image.objects.none())

        # 두 모델폼의 유효성 검사
        if postForm.is_valid() and formset.is_valid():
            post_form = postForm.save(commit=False)
            post_form.writer = request.user
            post_form.save()
            print("수정된 모델", post_form)

            # 처음에 보낸 폼과 내용이 달라진 경우 실행
            if formset.has_changed():
                files = Image.objects.filter(post=post_form)
                files.delete()

            # 이미지가 새롭게 들어오는 경우
            for form in formset.cleaned_data:
                if form:
                    image = form['image']
                    photo = Image(post=post_form, image=image)
                    photo.save()
            return redirect("post_detail", post_id=post_id)
        # 유효성 검사 실패시 터미널상에 에러메시지 print
        else:
            print(postForm.errors, formset.errors)
    else:
        # POST 요청이 아닌 경우
        postForm = PostForm(instance=post)
        formset = ImageFormSet(queryset=Image.objects.none())

    return render(request, 'community/post_edit.html',
                  {'postForm': postForm, 'formset': formset})


# 삭제
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    return redirect("post_list")


##### answer #####

# 댓글 등록
@login_required(login_url="login")
def answer_write(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.post = post
            answer.writer = request.user
            answer.save()
            return redirect(
                "{}#answer_{}".format(
                    resolve_url("post_detail", post_id=post_id), answer.id
                )
            )
    else:
        form = AnswerForm()
    return render(request, "community/post_detail.html", {"form": form, "post": post})


# 댓글 수정
def answer_edit(request, answer_id):
    answer = get_object_or_404(Answer, id=answer_id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.save()
            return redirect(
                "{}#answer_{}".format(
                    resolve_url("post_detail",
                                post_id=answer.post_id), answer.id
                )
            )
    else:
        form = AnswerForm(instance=answer)

    return render(request, "community/answer_form.html", {"form": form})


# 댓글 삭제
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, id=answer_id)
    answer.delete()
    return redirect("post_detail", post_id=answer.post_id)


##### comment #####

# 대댓글 등록
@login_required(login_url="login")
def comment_write(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.answer = answer
            comment.writer = request.user
            comment.save()
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("post_detail",
                                post_id=answer.post.id), comment.id
                )
            )
    else:
        form = CommentForm()

    return render(
        request, "community/comment_form.html", {
            "form": form, "answer": answer}
    )


# 대댓글 수정
def comment_edit(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.save()
            return redirect(
                "{}#answer_{}".format(
                    resolve_url("post_detail", post_id=comment.answer.post.id),
                    comment.id,
                )
            )
    else:
        form = CommentForm(instance=comment)

    return render(request, "community/comment_form.html", {"form": form})


# 대댓글 삭제
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect("post_detail", post_id=comment.answer.post_id)


##### 추천 #####


@login_required(login_url="login")
def vote_post(request, post_id):

    post = get_object_or_404(Post, id=post_id)

    # 질문 찾은 후 question.voter.add(로그인 사용자)
    # 자신의 글은 추천하지 못하도록
    if post.writer != request.user:
        post.vote.add(request.user)
    else:
        messages.error(request, "본인이 작성한 글은 추천할 수 없습니다.")

    return redirect("post_detail", post_id=post_id)


@login_required(login_url="login")

templates/community/answer_form.html
{% extends 'base.html' %}
{% block contents %}

  <div class="container my-3">
    <section class="pb-3 col-lg-8 col-md-10 mx-auto mt-5">
      <div class="card bg-light">
        <div class="card-body">
          <h5 class="border-bottom pb-2 mt-5 mb-5">
            댓글 수정
          </h5>
          {% include 'form_errors.html' %}
          <form method="post">
            {% csrf_token %}
            <div class="form-group mb-3">
              <label for="content" class='mb-1'>댓글 내용</label>
              <textarea name='content' id='content' rows='10' class='form-control'>{{form.content.value}}</textarea>
            </div>
            <button type='submit' class='btn btn-secondary' style='float:right; background-color:#675444; color:#fff'>수정 완료</button>
          </form>
        </div>
      </div>
    </section>
  </div>
{% endblock contents %}

templates/community/comment_form.html
{% extends 'base.html' %}
{% block contents %}
  <div class="container my-3">
    <section class="pb-3 col-lg-8 col-md-10 mx-auto mt-5">
      <div class="card bg-light">
        <div class="card-body">
          <h5 class="border-bottom pb-2 mt-5 mb-5">
            대댓글 등록
          </h5>
          {% include 'form_errors.html' %}
          <form method="post">
            {% csrf_token %}
            <div class="form-group mb-3">
              <label for="content" class='mb-1'>내용</label>
              <textarea name='content' id='content' rows='10' class='form-control'>{{form.content.value}}</textarea>
            </div>
            <button type='submit' class='btn btn-secondary' style='float:right; background-color:#675444; color:#fff'>대댓글 등록</button>
          </form>
        </div>
      </div>
    </section>
  </div>
{% endblock contents %}

templates/community/post_detail.html
{% extends 'base.html' %} {% load board_filter %} {% block style %}
<style>
  .bi-chat-square-heart {
    font-size: 30px;
    color: crimson;
  }

  {% comment %} .answer li {
    list-style: none;
  } {% endcomment %}

  .comment_create, .order {
    text-decoration: none;
    color: inherit;
  }
</style>
{% endblock style %} {% block contents %}
<div class="pt-3">
  <form class="col-lg-8 col-md-10 mx-auto">
    {% include 'form_errors.html' %}
    <div class="row mt-5 pt-3">
      <div class="row mt-3 mb-1">
        <div class="col-4">
          <h5 class="pb-2">
            <b>제목 : {{post.title}}</b>
          </h5>
        </div>
      </div>
      <hr class="one mb-3" />
      <div class="d-flex flex-row justify-content-between mb-5">
        <div class="py-2 text-muted">
          <!-- 작성날짜 -->
          <span>작성자 : {{post.writer}}</span>
          <span>({{post.created_at|date:'Y-m-d H:i'}})</span>
        </div>
        {% if post.modified_at %}
        <div class="pt-1">
          <div class="py-2 text-muted">
            <!-- 수정날짜 -->
            <div class="text-start">
              (수정 : {{post.modified_at|date:'Y-m-d H:i'}})
            </div>
          </div>
        </div>
        {% endif %}
      </div>
      <div class="col-12 mt-5 mb-5">
        {% if post.image %} {% for i in post.image.all %}
        <img
          src="{{i.image.url}}"
          alt=""
          class="mx-auto d-block"
          style="width: 600px"
        /><br />
        {% endfor %} {% endif %} {% comment %} {% if post.image %}
        <img src="{{post.image.url}}" alt="" class="mx-auto d-block" />
        {% endif %} {% endcomment %}
      </div>
      <div class="col-12 mb-5">
        <p>{{post.content}}</p>
      </div>
      <a href="#" data-uri="{% url 'vote_post' post.id %}" class="recommend btn mx-auto d-block"><i class="bi bi-chat-square-heart"></i></a>
      <hr class="one mt-5 mb-5" />

    </div>
    <div class="d-flex mb-5">
      <div class='me-auto'>
        {% if post.get_previous %}
        <div> 
          <a href="{{post.get_previous.get_absolute_url}}" class='order'>이전글 : {{post.get_previous}}</a>
        </div>
        {% endif %}
        {% if post.get_next %}
        <div> 
          <a href="{{post.get_next.get_absolute_url}}" class='order'>다음글 : {{post.get_next}}</a>
        </div>
        {% endif %}
      </div>
      <div>
        {% if post.writer == request.user %}
        <a href="#" class="btn btn-sm btn-outline-secondary delete" data-uri="{% url 'post_delete' post.id %}">삭제</a>
        <a href="{% url 'post_edit' post.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
        {% endif %}
        <a href="#" class="btn btn-sm btn-outline-secondary list" style="background-color:#675444; color:#fff" data-uri="{% url 'post_list' %}">목록으로</a>
      </div>
    </div>
  </form>
    <!-- 댓글 영역 -->
    <section class="pb-3 col-lg-8 col-md-10 mx-auto mb-5">
      <div class="card bg-light">
        <div class="card-body">
          <!-- 댓글 작성 폼 -->
          <h5 class="my-3 py-2">
            <!-- 댓글 개수 -->
            {{post.answer_set.count}} 개의 댓글이 있습니다.
          </h5>
          {% include 'form_errors.html' %}
          <div class="row mb-5">
            <form action="{% url 'answer_write' post.id %}" method="post">
              {% csrf_token %}
              <div class="form-group mb-3">
                <textarea name="content" id="content" rows="3" class="form-control"></textarea>
              </div>
              <button type="submit" class="btn btn-sm btn-outline-secondary" style="float: right">
                댓글 쓰기
              </button>
            </form>
          </div>
          {% comment %}
          <hr class="one mb-3" />
          {% endcomment %} {% for answer in post.answer_set.all %}
          <a name="answer_{{answer.id}}"></a>
          <div class="row">
            <div class="col-12 mb-3">
              <div class="border-top pt-3">
                <div>
                  <!-- 댓글 내용 -->
                  {{answer.content|mark}}
                </div>
                {% comment %} <div class="d-flex justify-content-end">
                  <div class="badge bg-secondary p-2">
                    <!-- 댓글 작성날짜 -->
                    작성 날짜 : {{answer.created_at|date:'Y-m-d H:i'}}
                  </div>
                </div>
                {% if answer.modified_at %}
                <div class="d-flex justify-content-end pt-1">
                  <div class="badge bg-secondary p-2">
                    <!-- 댓글 수정날짜 -->
                    <div class="text-start">
                      수정 : {{answer.modified_at|date:'Y-m-d H:i'}}
                    </div>
                  </div>
                </div>
                {% endif %} {% endcomment %}
                <div class='text-muted'>{{answer.writer}} {{answer.created_at|date:'Y-m-d H:i'}} (수정 : {{answer.modified_at|date:'Y-m-d H:i'}})</div>
                <div class="my-3">
                  {% if answer.writer == request.user %}
                  <a href="{% url 'answer_edit' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                  <a href="#" class="btn btn-sm btn-outline-secondary delete" data-uri="{% url 'answer_delete' answer.id %}">삭제</a>
                  {% endif %}
                  <a href="{% url 'comment_write' answer.id %}" class="btn btn-sm btn-outline-secondary">대댓글</a>
                  <a href="{% url 'vote_answer' answer.id %}" class="recommend btn btn-outline-secondary btn-sm ms-3">추천 : {{answer.vote.count}}</a>
                </div>
                <!-- 대댓글 -->
                {% if answer.comment_set.count > 0 %}
                <div class="mt-3 ms-5">
                  {% for comment in answer.comment_set.all %}
                  <!-- 앵커 부분 -->
                  <a name="comment_{{comment.id}}"></a>
                  <div class="comment py-2 text-muted">
                    <i class="bi bi-arrow-return-right"></i>
                    <span style="white-space: pre-line">{{comment.content}}</span>
                    <span>- {{comment.writer}} {{comment.created_at|date:'Y-m-d H:i'}} (수정 : {{comment.modified_at|date:'Y-m-d H:i'}})</span>
                    <!-- 대댓글 작성자와 로그인 사용자가 같다면 -->
                    {% if comment.writer == request.user %}
                    <a href="{% url 'comment_edit' comment.id %}" class="btn btn-sm btn-outline-secondary ms-3">수정</a>
                    <a href="#" data-uri="{% url 'comment_delete' comment.id %}" class="btn btn-sm btn-outline-secondary delete">삭제</a>
                    {% endif %}
                    <a href="{% url 'vote_comment' comment.id %}" class="recommend btn btn-outline-secondary btn-sm ms-3">추천 : {{comment.vote.count}}</a>
                  </div>
                  {% endfor %}
                </div>
                {% endif %}
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>
  
  <!-- 댓글 영역 종료 -->
</div>
{% endblock contents %} {% block script %}
<script>
  // 목록
  document
    .querySelector(".list")
    .addEventListener("click", () => (location.href = "{% url 'post_list' %}"));

  // 삭제
  let elements = document.querySelectorAll(".btn-danger, .delete");
  elements.forEach((ele, idx) => {
    ele.addEventListener("click", (e) => {
      if (confirm("정말로 삭제하시겠습니까?")) {
        location.href = e.target.dataset.uri;
      }
    });
  });

  // 추천 버튼 클릭 시 '정말로 추천하시겠습니까?'
  $(".recommend").on("click", function (e) {
    if (confirm("정말로 추천하시겠습니까?")) {
      location.href = $(this).data("uri");
    }
  });
</script>
{% endblock script %}

templates/community/post_edit.html
{% extends 'base.html' %}
{% block contents %}
  <div class="container">
    <h4 class="pb-2 mb-5 mt-5">
      글 수정
    </h4>
    {% include 'form_errors.html' %}
    <form method="post" class='row' enctype='multipart/form-data'>
      {% csrf_token %}
      <div class="form-group mb-5 col-6">
        <label for="title">제목</label>
        <input type="text" name='title' id='title' class='form-control mt-1' value="{{postForm.title.value}}">
      </div>
      <div class="form-group mb-5">
        <label for="content">내용</label>
        <textarea name='content' id='content' rows='13' class='form-control mt-1'>{{postForm.content.value}}</textarea>
      </div>
     
      <div>
        {{ formset.management_form }}
        {% for form in formset %}
            {{ form }}<br />
        {% endfor %}
      </div>
        
      {% comment %} <div class='d-flex'>
        <div class="form-group mb-5 col-3 ms-auto">
          <label for="image">사진첨부</label>
          <input type="file" name='image' id='image' class='form-control mt-1' value="{{form.image.value}}">
        </div>
      </div> {% endcomment %}
      
      <div class="text-center">
        <button type="submit" class="btn mt-2 mb-5" style="background-color:#675444; color:#fff">수정 완료</button>
      </div>
    </form>
  </div>
{% endblock contents %}

templates/community/post_write.html
{% extends 'base.html' %}
{% block contents %}
  <div class="container">
    {% include 'form_errors.html' %}
    <div class="container" style="width:80%">
      <h4 class="pb-2 mb-2 mt-5">
        <strong>게시글 작성</strong>
      </h4>
      <hr>
      <form method="post" class='row' id="post_form" enctype='multipart/form-data'>
        {% csrf_token %}
        <div class="form-group mb-3 col-6">
          <label for="title">제목</label>
          <input type="text" name='title' id='title' class='form-control mt-1' value="">
        </div>
        <div class="form-group mb-3">
          <label for="content">내용</label>
          <textarea name='content' id='content' rows='13' class='form-control mt-1'></textarea>
        </div>
        <div>
          {{ formset.management_form }}
          {% for form in formset %}
              {{ form }}<br />
          {% endfor %}
        </div>
        {% comment %} <div id='image_preview'>
          <input type='file' name='image' id='btnAtt' onchange='setThumbnail(event)' multiple='multiple' accept='image/*'/>
          <div id='att_zone'
                data-placeholder='파일 선택 버튼을 클릭하거나 파일을 드래그앤드롭 하세요'></div>
        </div> {% endcomment %}
      
        <div class="mt-2 mb-5">
          <button type="submit" class="btn" style="background-color:#675444; color:#fff">게시글 작성</button>
        </div>
      </form>
    </div>
  </div>
{% endblock contents %}