config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="main"),
    path("generic/", TemplateView.as_view(template_name="generic.html"), name="generic"),
    path("elements/", TemplateView.as_view(template_name="elements.html"),
         name="elements"),
    path("todo_list/", include('todo_list.urls')),
    path("board/", include('board.urls')),
    path("find/", include('find.urls')),
    # path("chat/", include('chat.urls') ),
    path("community/", include('community.urls')),
    path("maps/", include('map.urls')),
    # path("ranking/", include('ranking.urls') ),
    path("todo_list/", include('todo_list.urls')),
    path("users/", include('user.urls')),
    path("volunteer/", include('volunteer.urls')),

    # google login
    path("accounts/", include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

find/urls.py
from django.urls import path
from .import views
from django.views.generic import TemplateView
# from board.views import list


urlpatterns = [
    # board
    path("index/", views.home, name="find_index"),

    path("detail/<int:pk>/", views.detail, name="find_detail"),
    path("write", views.update, name="find_write"),
    path("delete/<int:pk>/", views.remove, name="find_remove"),
    path("edit/<int:pk>/", views.edit, name="find_edit"),

    # 댓글
    path("comment/create/<int:pk>/", views.comment_create,
         name="find_comment_create"),

    path("<int:post_pk>/comment/<int:comment_pk>/remove/",
         views.comment_remove, name="find_comment_remove"),
    path("comment/<int:post_pk>/update/<int:comment_pk>",
         views.comment_update, name="find_comment_update"),
    # 검색
    #     path('search/', views.search, name="find_search"),
    # 추천수
    path('like/<int:post_id>/', views.vote_question, name="find_vote_question"),



    # 대댓글
    #     path("comment/<int:pk>/recreate/<int:comment_pk>",
    #          views.recomment_update, name="recomment_update"),

]

map/urls.py
from django.urls import path
from .import views
# from board.views import list


urlpatterns = [
    path("", views.maps, name="maps"),
]

board/models.py
from django.db import models
from user.models import User
from django.urls import reverse
# from imagekit.models import ImageSpecField
# from imagekit.processors import Thumbnail
# from imagekit.processors import ResizeToFill
# Create your models here.


class Care(models.Model):
    title = models.CharField(max_length=30)
    place = models.CharField(max_length=15)
    content = models.TextField(null=True, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(blank=True, null=True, verbose_name="이미지")
    updated_at = models.DateTimeField(auto_now=True)
    best = models.ManyToManyField(
        User, related_name="best", verbose_name="추천수")
    view_count = models.IntegerField(default=0)
    writer = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="작성자")
    comment_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("board_detail", args=[self.pk])

    def get_previous(self):
        return self.get_previous_by_created_at()

    def get_next(self):
        return self.get_next_by_created_at()


class CareCount(models.Model):
    ip = models.CharField(max_length=30)
    question = models.ForeignKey(Care, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.ip


class Comment(models.Model):
    writer = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="작성자")
    contents = models.TextField(verbose_name="내용")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성날짜")
    modified_at = models.DateTimeField(auto_now=True, verbose_name="수정날짜")
    post = models.ForeignKey(
        Care, on_delete=models.CASCADE, null=True, blank=True)
    comment_count = models.IntegerField(default=0)


class ReComment(models.Model):
    writer = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="작성자")
    content = models.TextField(verbose_name='대댓글')
    created_at = models.DateTimeField(verbose_name='작성날짜', auto_now_add=True)
    modified_at = models.DateTimeField(verbose_name='수정날짜', auto_now=True)
    answer = models.ForeignKey(
        Comment, on_delete=models.CASCADE, null=True, blank=True)

find/models.py
from django.db import models
from django.db import models
from user.models import User
from django.urls import reverse

class Find(models.Model):
    title = models.CharField(max_length=30)
    place = models.CharField(max_length=15)
    content = models.TextField(null=True, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(blank=True, null=True, verbose_name="이미지")
    updated_at = models.DateTimeField(auto_now=True)
    voter = models.ManyToManyField(
        User, related_name="find_voter", verbose_name="추천수")
    view_count = models.IntegerField(default=0)
    writer = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="작성자")
    comment_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("find_detail", args=[self.pk])

    def get_previous(self):
        return self.get_previous_by_created_at()

    def get_next(self):
        return self.get_next_by_created_at()
class FindComment(models.Model):
    writer = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="작성자")
    contents = models.TextField(verbose_name="내용")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성날짜")
    modified_at = models.DateTimeField(auto_now=True, verbose_name="수정날짜")
    post = models.ForeignKey(
        Find, on_delete=models.CASCADE, null=True, blank=True)
    comment_count = models.IntegerField(default=0)


class FindReComment(models.Model):
    writer = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="작성자")
    content = models.TextField(verbose_name='대댓글')
    created_at = models.DateTimeField(verbose_name='작성날짜', auto_now_add=True)
    modified_at = models.DateTimeField(verbose_name='수정날짜', auto_now=True)
    answer = models.ForeignKey(
        FindComment, on_delete=models.CASCADE, null=True, blank=True)

find/forms.py
from django import forms
from find.models import Find, FindComment


class FindForm(forms.ModelForm):
    class Meta:
        model = Find
        fields = ["title", "place", "content", "image"]


class FindCommentForm(forms.ModelForm):
    class Meta:
        model = FindComment
        fields = ['contents']


# class ReCommentForm(forms.ModelForm):
#     class Meta:
#         model = ReComment
#         fields = ['body', 'Comment']

find/views.py
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from django.contrib.auth.decorators import login_required
from find.models import Find, FindComment, FindReComment
from .forms import FindCommentForm, FindForm
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.contrib import messages


def home(request):
    posts = Find.objects.order_by('-created_at')

    # 정렬 기준
    sort = request.GET.get('sort', "created_at")
    # 검색어 받기
    keyword = request.GET.get("keyword", "")
    # 검색기준 : 댓글순, 추천수, 최신순
    search_kinds = request.POST.get('search_kinds', "")

    if sort == 'view_count':
        posts = Find.objects.order_by('-view_count', '-created_at')
    elif sort == 'comment_count':
        posts = Find.objects.order_by('-comment_count', '-created_at')
        # posts = Find.objects.annotate(com_cut=Count(
        #     'comment')).order_by('-com_cut', '-created_at')
    elif sort == 'voter':
        posts = Find.objects.order_by('-voter', '-created_at')
        # posts = Find.objects.annotate(best_cnt=Count(
        #     'voter')).order_by('-best_cnt', '-created_at')
    else:
        posts = Find.objects.order_by('-created_at')

    # 검색어가 들어간 리스트만 추출
    if keyword:
        if search_kinds == 'all':
            posts = posts.filter(Q(title__icontains=keyword) | Q(content__icontains=keyword) | Q(
                place__icontains=keyword) | Q(writer__name__icontains=keyword)).distinct()

        elif search_kinds == "title":
            posts = posts.filter(title__icontains=keyword).distinct()

        elif search_kinds == "writer":
            posts = posts.filter(writer__name__icontains=keyword).distinct()

        elif search_kinds == "content":
            posts = posts.filter(content__icontains=keyword).distinct()
        else:
            posts = posts.filter(place__icontains=keyword).distinct()

    # 현재 페이지 번호
    page = request.GET.get("page", 1)

    paginator = Paginator(posts, 4)
    list = paginator.get_page(page)

    return render(request, 'find/find_index.html', {'list': list, 'sort': sort, 'page': page, 'keyword': keyword})


# 글작성


@login_required(login_url="login")
def update(request):
    if request.method == "POST":
        form = FindForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post. writer = request.user
            post.save()
            form.save_m2m()
            return redirect("find_index")
    else:
        form = FindForm()
    return render(request, "find/find_write.html", {"form": form})

# 글 디테일


def detail(request, pk):
    post = get_object_or_404(Find, pk=pk)
    default_view_count = post.view_count
    post.view_count = default_view_count + 1
    post.save()
    return render(request, "find/find_detail.html", {"post": post})


#  글 삭제
@login_required(login_url="login")
def remove(request, pk):
    post = get_object_or_404(Find, pk=pk)
    post.delete()
    return redirect("find_index")

# 글 수정


@login_required(login_url="login")
def edit(request, pk):
    post = Find.objects.get(pk=pk)
    if request.method == "POST":
        form = FindForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.writer = request.user
            post.save()
            form.save_m2m()
            return redirect("find_index")
    else:
        form = FindForm(instance=post)
    return render(request, "find/find_edit.html", {"form": form})


# 댓글작성
@login_required(login_url="login")
def comment_create(request, pk):
    """
    댓글내용, 원본글 번호, 작성자(로그인 사용자)
    """
    post = get_object_or_404(Find, pk=pk)
    post.comment_count = post.comment_count + 1
    post.save()

    if request.method == "POST":
        comment = FindComment()
        comment.post = post
        comment.writer = request.user
        comment.contents = request.POST['contents']
        comment.save()

    return redirect("find_detail", post.pk)

# 댓글삭제


@login_required(login_url="login")
def comment_remove(request, post_pk, comment_pk):
    comment = get_object_or_404(FindComment, pk=comment_pk)
    comment.delete()

    return redirect('find_detail', post_pk)


# 댓글 수정
@login_required(login_url="login")
def comment_update(request, post_pk, comment_pk):
    comment = FindComment.objects.get(pk=comment_pk)
    if request.method == "POST":
        form = FindCommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.writer = request.user
            # comment.contents = request.POST['contents']
            comment.save()
            return redirect("find_detail", post_pk)
    else:
        form = FindForm(instance=comment)
    return render(request, "find/find_comment_update.html", {"form": form})


# 대댓글

# # 검색기능
# def search(request):
#     blogs = Find.objects.all().order_by('-id')

#     # 검색어
#     q = request.POST.get('q', "")
#     # 검색기준
#     search_kinds = request.POST.get('search_kinds', "")

#     if q:
#         if search_kinds == 'all':
#             blogs = blogs.filter(Q(title__icontains=q) | Q(content__icontains=q) | Q(
#                 place__icontains=q) | Q(writer__username__icontains=q)).distinct()

#         elif search_kinds == "title":
#             blogs = blogs.filter(title__icontains=q).distinct()

#         elif search_kinds == "writer":
#             blogs = blogs.filter(writer__username__icontains=q).distinct()

#         elif search_kinds == "content":
#             blogs = blogs.filter(content__icontains=q).distinct()
#         else:
#             blogs = blogs.filter(place__icontains=q).distinct()

#         page = request.GET.get("page", "")
#         paginator = Paginator(blogs, 9)
#         blogs = paginator.get_page(page)
#         return render(request, 'find/find_search.html', {'blogs': blogs, 'q': q, 'search_kinds': search_kinds})

#     else:
#         return render(request, 'find/find_search.html')


@login_required(login_url="login")
def vote_question(request, post_id):
    """
    질문 추천 등록 / 성공 시 detail
    질문 찾은 후 question.vote.add(로그인 사용자)
    """

    post = get_object_or_404(Find, id=post_id)

    # 자신의 글은 추천하지 못하고 타인이 쓴 글만 추천 가능
    if post.writer != request.user:
        post.voter.add(request.user)
    else:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')

    return redirect("find_detail", pk=post_id)

templates/find/find_detail.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  <style>
    .order {
      text-decoration: none;
      color: inherit;
    }
  </style>
{% endblock style %}
{% block contents %}

  {% include "form_errors.html" %}
  <!-- 폼 요소에 type='file' 포함이 되어 있다면 form enctype(인코딩타입) 속성 필요함 text 형태의 데이터 전송 시 enctype 타입은 application/x-www-form-urlencode(기본) 설정되어있음 -->
  <div class="pt-3">
    <form method="POST" class="col-lg-8 col-md-10 mx-auto" enctype="multipart/form-data">

      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <p class="card-text">
        </p>
      </div>
      <div class="row mt-5 pt-3">
        <div class='row mt-3 mb-1'>
          <div class="col-4">
            <h5 class="pb-2">
              <b>제목 :
                {{post.title}}</b>
            </h5>
          </div>
        </div>
        <hr class='one mb-3'>
        <div class="d-flex flex-row justify-content-between mb-5">
          <div class="py-2 text-muted">
              <!-- 작성날짜 -->
              <span>작성자 : {{post.writer}}</span>
              <span>({{post.created_at|date:'Y-m-d H:i'}})</span>
          </div>
          {% if post.updated_at %}
            <div class="pt-1">
              <div class="py-2 text-muted">
                <!-- 수정날짜 -->
                <div class="text-start">(수정 : {{post.updated_at|date:'Y-m-d H:i'}})</div>
              </div>
            </div>
            {% endif %}
        </div>
        <div class="col-12 mt-5 mb-5">
          {% if post.image %}
          <img  class='mx-auto d-block detail_img' src="{{post.image.url}}" alt="">
          {% endif %}
        </div>
        <div class="col-12">
          <p>{{post.content}}</p>
        </div>
        <div>
          <a href="#" data-uri="{% url 'find_vote_question' post.id %}" class="recommend btn mx-auto d-block"><i class="bi bi-chat-square-heart"></i></a>
        </div>
        <hr class='one mt-5 mb-5'>
      </div>


      <div class="d-flex mb-5">
        <div class='me-auto'>
          {% if post.get_previous %}
          <div> 
            <a href="{{post.get_previous.get_absolute_url}}" class='order'>이전글 : {{post.get_previous}}</a>
          </div>
          {% endif %}
          {% if post.get_next %}
          <div> 
            <a href="{{post.get_next.get_absolute_url}}" class='order'>다음글 : {{post.get_next}}</a>
          </div>
          {% endif %}
        </div>

      <div class="">
        {% if post.writer == request.user %}
        <a href="#" class="btn btn-sm btn-outline-secondary delete" data-uri="{% url 'find_remove' post.pk %}">삭제</a>
        <a href="{% url 'find_edit' post.pk %}" class="btn btn-sm btn-outline-secondary">수정</a>
        {% endif %}
        <a href="{% url 'find_index' %}" class="btn list" style="background-color:#675444; color:#fff" data-uri="#">목록으로</a>
      </div>
    </div>

      <!--원본 글 수정/삭제-->

      </form>
    </div>

    <!--댓글 달기-->

    <section class="pb-3 col-lg-8 col-md-10 mx-auto">
      <div class="card bg-light">
        <div class="card-body">
          <p>
            <span class="text-danger small mx-2">댓글 [{{post.findcomment_set.count}}]</span>
            <form method="POST" action="{% url 'find_comment_create' post.pk   %}">
              {% csrf_token %}
              <!-- Comment form-->
              <textarea class="form-control" name="contents" id="contents" rows="3" placeholder="댓글!"></textarea>
              <p>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                  <div class="form-group">
                    <input class="btn btn-outline-secondary btn-sm" type="submit" value="댓글작성"/>
                  </div>
                </form>
              </div>

              {% for comment in post.findcomment_set.all %}
                <div class="d-flex mt-4">
                  <div class="flex-shrink-0">
                    
                    {{comment.writer}}:{{comment.contents}}
                    
                    <!--원본 글 수정/삭제-->
                    <a class="btn btn-outline-secondary btn-sm" href="{% url 'find_comment_remove' post.pk comment.pk %}">x</a>
                    <a href="#" class="btn btn-outline-secondary btn-sm update">수정</a>
                    <a href="{% url 'comment_write' post.pk comment.pk %}" class="btn btn-outline-secondary btn-sm reupdate">대댓글</a>

                  </div>
                </div>
                <!-- 수정 폼-->
                <div style="display:none" id="updateForm">
                  <form method="POST" action="{% url 'find_comment_update' post.pk comment.pk %}">
                    {% csrf_token %}
                    <!-- Comment form-->
                    <textarea class="form-control" name="contents" id="contents" rows="3" placeholder="댓글!"></textarea>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                      <div class="form-group">
                        <input class="btn btn-outline-secondary btn-sm" type="submit" value="댓글수정"/>
                      </div>
                    </div>
                  </form>
                </div>
                {% comment %} 대댓글폼 {% endcomment %}
                <div style="display:none" id="reupdateForm">
                  <form method="POST" action"">
                    {% csrf_token %}
                    <!-- Comment form-->
                    <textarea class="form-control" name="contents" id="contents" rows="3" placeholder="Join the discussion and leave a comment!"></textarea>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                      <div class="form-group">
                        <input class="btn btn-outline-secondary btn-sm" type="submit" value="대댓글달기"/>
                      </div>
                    </div>
                  </form>
                </div>

              {% endfor %}
            </div>
          </div>
        </div>
      </section>
    {% endblock contents %}

    {% block script %}
      <script>
        $(".update").on("click", function (e) {
          e.preventDefault();
          $("#updateForm").css("display", "block");
        })
     
        $(".reupdate").on("click", function (e) {
          e.preventDefault();
          $("#reupdateForm").css("display", "block");
        })
        // 삭제
    let elements = document.querySelectorAll('.btn-danger, .delete');
    elements.forEach((ele, idx) => {
      ele.addEventListener('click', (e) => {
        if (confirm('정말로 삭제하시겠습니까?')) {
          location.href = e.target.dataset.uri;
        }
      })
    })
    // 추천 버튼 클릭 시 '정말로 추천하시겠습니까?'
    $('.recommend').on('click', function (e) {
      if (confirm('정말로 추천하시겠습니까?')) {
        location.href = $(this).data('uri');
      }
    })


      </script>
    </div>
  </div>
</div>
</section>
{% endblock script %}

templates/find/find_index.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<style>
  .fa-solid {
    color:#675444 ;
  }
</style>
<script src="https://kit.fontawesome.com/482f2e22f6.js" crossorigin="anonymous"></script>
{% endblock style %}
{% block contents %}
<div class="container my-3">
  <div class='pt-5'>
    <div class="d-flex justify-content-center mt-5 mb-5">
      <a href="{% url 'find_index' %}" class='move'>
        <h1><i class="fa-solid fa-paw"></i> <strong>임보/입양</strong> <i class="fa-solid fa-paw"></i></h1>
      </a>
    </div>
    <hr style="width:40rem; margin: 0 auto;"/>
    <div class="d-flex justify-content-center mt-5 mb-5">
      {% if keyword %}
        <h5>'{{keyword}}' 검색 결과입니다.</h5>
      {% endif %}
    </div>
  </div>
  <div class="d-flex mt-5 mb-3">
    <!-- 정렬 -->
    <div class="col-1 me-auto">
      <select name="" id="sort" class="form-control sort text-center">
        <option value="created_at" {% if sort == 'created_at' %}selected{% endif %}>최신순</option>
        <option value="voter" {% if sort == 'voter' %}selected{% endif %}>추천순</option>
        <option value="comment_count" {% if sort == 'comment_count' %}selected{% endif %}>인기순</option>
      </select>
    </div>
    <!-- 검색 -->
    <div class="col-1 me-2">
      <select name="" id="search_kind" class="form-control text-center">
        <option value="all" selected="selected">전체</option>
        <option value="title"{% if search_kind == 'title' %}selected{% endif %}>제목</option>
        <option value="writer"{% if search_kind == 'writer' %}selected{% endif %}>작성자</option>
        <option value="content"{% if search_kind == 'content' %}selected{% endif %}>내용</option>
        <option value="place"{% if search_kind == 'place' %}selected{% endif %}>장소</option>
      </select>
    </div>
    <div class="col-2 mb-3">
      <div class="input-group">
        <input onkeyup='enterkey()' type="text" name="keyword" id="keyword" class="form-control" value="{{keyword|default_if_none:''}}">
        <button type="button" class="btn btn-outline-secondary search">검색</button>
      </div>
    </div>
  </div>
    <div class="row row-cols-1 row-cols-md-4 g-4">
      {% for care in list %}
      <div class="col">
        <div class="card h-100" style="height: 486px;">
          <a href="{% url 'find_detail' care.pk %}" class="move">
            {% if care.image %}
            <img src="{{care.image.url}}" alt="" class="card-img-top">
            {% endif %}
            <div class="card-body">
              <p>
                <b class="card-title">{{care.title}}</b>
                
                <span class="text-danger small mx-2">[{{care.findcomment_set.count}}]</span>
               
              </p>
              <p class="card-text">
                <small><i>장소 : {{care.place}}</i></small></br>
                <small><i>아이디 : {{care.writer.email}}</i></small></br>
                <small><i>조회수 : {{care.view_count}}</i></small></br>
                <small>
                  <i>추천수 :
                    {% if care.voter.count %}
                    <span class="badge bg-warning px-2 py-1">{{care.voter.count}}</span>
                    {% endif %}
                  </i>
                </small>
              </p>
            </div>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="mt-3" style="float: right">
      <a href="{% url 'find_write' %}" class="btn" style="background-color:#675444; color:#fff"  >글 작성</a>
    </div>
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center mb-5">
        {% if list.has_previous %}
          <li class="page-item">
            <a class="page-link" href="#" data-page="{{list.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        {% endif %}
        {% for page in list.paginator.page_range %}
          {% if page >= list.number|add:-5 and page <= list.number|add:5 %}
            <li class="page-item {% if page == list.number %}active{% endif %}">
              <a class="page-link" href="#" data-page="{{page}}">{{page}}</a>
            </li>
          {% endif %}
        {% endfor %}
        {% if list.has_next %}
          <li class="page-item">
            <a class="page-link" href="#" data-page="{{list.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
</div>
  <!-- 검색시 동작하는 폼-->
  <form action="{% url 'find_index' %}" id="searchForm">
    <input type="hidden" name='keyword' value="{{keyword|default_if_none:''}}" class='keyword'>
    <input type="hidden" name='page' value="{{page|default_if_none:''}}" id='page'>
    <input type="hidden" name='sort' value="{{sort|default_if_none:''}}" id='sort'>
  </form>

{% endblock contents %}
{% block script %}
  <script>
    const searchform = document.querySelector("#searchForm")
    // 검색버튼 클릭 시
    document.querySelector(".search").addEventListener("click",()=>{
      // 사용자가 입력한 검색어 가져오기
      let keyword = document.querySelector("#keyword").value;
      // 가져온 검색어를 searchForm 안의 keyword value 값으로 지정하고 page 값 을 1로 지정
      document.querySelector("#searchForm > .keyword").value = keyword;
      document.querySelector("#searchForm > #page").value = 1;
      // searchForm 전송
      searchform.submit();
    })
    let page_link = document.querySelectorAll(".page-link")
    page_link.forEach((obj,idx)=>{
      obj.addEventListener("click",(e)=>{
        console.log(e.target.dataset.page)
        document.querySelector("#searchForm > #page").value = e.target.dataset.page;
        // searchForm 전송
        searchform.submit();
      })
    })
    document.querySelector("#sort").addEventListener('change',(e)=>{
      document.querySelector("#searchForm > #sort").value = e.target.value;
      searchform.submit();
    })

    let post_list = document.querySelectorAll('td>a.nav-link')
    post_list.forEach((post,idx)=>{ 
      post.addEventListener('click',(e)=>{
        // 제목 클릭시 a 태그 기능 중지
      e.preventDefault()
      // a태그의 href 값 가져오기
      console.log(e.target.href)
      searchform.setAttribute("action", e.target.getAttribute("href"))
      searchform.submit();
    })
  })
  </script>
{% endblock script %}

templates/find/find_search.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}

  <body>
    {% for posts in blogs %}
      {% if forloop.counter0 | divisibleby : 3 %}
        <div class="row my-3">
        {% endif %}
        <div class="col-md-3" style='float:none; margin:0 auto;' id="">
          <div class="card" style="width: 18.9rem;">
            {% if posts.image %}
              <img src="{{posts.image.url}}" alt="" class="card-img-top">
            {% endif %}
            <div class="card-body"></div>
            <p class="card-text" style="font-weight: bold;">{{posts.title}}
              {% if pots.comment_set.count > 0 %}
                <span class="text-danger small mx-2">[{{posts.comment_set.count }}]</span>
              {% endif %}
            </p>
            <p class="card-text">
              <small>
                <i>장소:
                  {{posts.place}}</i>
              </small>
            </p>
            <p class="card-text">
              <small>
                <i>아이디:
                  {{user.username}}</i>
              </small>
            </p>
            <p class="card-text">
              <small>
                <i>조회수:
                  {{posts.view_count}}</i>
              </small>
            </p>

            <p class="">
              <a href="{% url 'find_detail' posts.pk %}" class="btn text-white" style="background-color: gray;">보러가기</a>
            </p>
          </div>
        </div>
        {% if forloop.counter0 | add : "1" | divisibleby : 3 %}
        </div>
      {% endif %}
    {% endfor %}

    <div class="row">
      <div class="col-sm-12 text-center">
        <div class="pagination">
          <span class="step-links text-center" style="width:100%;">
            {% if blogs.has_previous %}
              <a href="?page=1">&laquo;</a>
              <a href="?page={{ blogs.previous_page_number }}">{{ blogs.previous_page_number }}</a>
            {% endif %}

            <span class="current">
              {{ blogs.number }}
            </span>

            {% if blogs.has_next %}
              <a href="?page={{ blogs.next_page_number }}">{{ blogs.next_page_number }}</a>
              <a href="?page={{ blogs.paginator.num_pages }}">&raquo;</a>
            {% endif %}
          </span>
        </div>
      </div>
    </div>
  </div>

</body>

{% endblock contents %}